### ISSUE TITLE
2023-24 Rosters

### ISSUE THREAD

**Issue by silfornia** [lbenz730/ncaahoopR#114]
Been consistently getting these errors when trying to pull rosters this year. Is this an issue on ESPN's side?

"Unable to get roster. ESPN is updating CBB files. Check back again soon."

Full code below. Not an urgent issue at all since I can get roster info from boxscores but this would help double check things.

Thanks!
Mike

<img width="676" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/8551f384-c38c-4dd8-bba6-3bb3967c62ed">

**Comment by lbenz730** [comment]
Should be working fine in latest version of the package. Just make sure you have that installed.

**Comment by silfornia** [comment]
Checked I was up to date on the hoopR version and re-ran. Still getting this error. Something else I'm doing wrong?

<img width="685" alt="image" src="https://github.com/lbenz730/ncaahoopR/assets/32369650/07f54475-5ef7-47f7-b7fc-cd215c793162">

**Comment by lbenz730** [comment]
Ah i see the issue. `ids[team_i, 1]` is a df not a charafter. Do it like this

```
library(ncaahoopR)

loopmatrix <- 1:nrow(ids)

for(team_i in loopmatrix) {
  team_roster <- get_roster(ids$team[team_i], '2023-24')
  ...
}
```

**Comment by silfornia** [comment]
That fixed the issue. Weird that my code worked for old seasons but not 2023. Thanks Luke!
